export type AppointmentStatus =
  | 'Available' | 'Booked' | 'Arrived' | 'In Progress'
  | 'Completed' | 'DNA' | 'Cancelled' | 'Blocked' | 'Reserved' | 'Running Late';

export type InteractionStatus = 'To do' | 'In progress' | 'Completed';

export type RoleCategory = 'doctor' | 'nurse' | 'hca' | 'clinic' | 'service';

export interface ScheduleColumn {
  id: string;
  name: string;
  role: string;
  category: RoleCategory;
  initials: string;
  sessionLabel?: string;
}

export interface ScheduleSlot {
  id: string;
  columnId: string;
  type: 'appointment' | 'blocked' | 'available' | 'task' | 'contact' | 'review' | 'follow-up';
  startTime: string;
  durationMins: number;
  patientName?: string;
  appointmentType?: string;
  status?: AppointmentStatus;
  blockedLabel?: string;
  chiNumber?: string;
  phone?: string;
  notes?: string;
  title?: string;             // what needs to happen (for interaction types)
  interactionStatus?: InteractionStatus;
  assignedTo?: string;        // staff member name
}

export const SCHEDULE_COLUMNS: ScheduleColumn[] = [
  { id: 'malik',      name: 'Dr Sarah Malik',    role: 'GP',                    category: 'doctor',  initials: 'SM', sessionLabel: 'Full Day Session'     },
  { id: 'reid',       name: 'Dr James Reid',     role: 'GP',                    category: 'doctor',  initials: 'JR', sessionLabel: 'Full Day Session'     },
  { id: 'wilson',     name: 'Amy Wilson',        role: 'Practice Nurse',        category: 'nurse',   initials: 'AW', sessionLabel: 'Full Day Session'     },
  { id: 'douglas',    name: 'Mark Douglas',      role: 'Healthcare Assistant',  category: 'hca',     initials: 'MD', sessionLabel: 'Full Day Session'     },
  { id: 'phlebotomy', name: 'Phlebotomy Clinic', role: 'Blood tests',           category: 'service', initials: 'PH', sessionLabel: 'Morning Session'      },
  { id: 'diabetes',   name: 'Diabetes Clinic',   role: 'Long-term conditions',  category: 'clinic',  initials: 'DC', sessionLabel: 'Afternoon Session'    },
];

export const SCHEDULE_SLOTS: ScheduleSlot[] = [
  // ─── Dr Sarah Malik ──────────────────────────────────────────────────────
  { id: 'sm-01', columnId: 'malik', type: 'appointment', startTime: '09:00', durationMins: 10, patientName: 'WALSH, Peter (Mr)',       appointmentType: 'Routine',            status: 'Completed',    chiNumber: '312748 5091', phone: '07891 234 560', notes: 'Routine appointment. Patient reporting persistent fatigue and low mood over the past three weeks. FBC and TFTs ordered. Follow-up in four weeks.' },
  { id: 'sm-02', columnId: 'malik', type: 'appointment', startTime: '09:10', durationMins: 10, patientName: 'DOBSON, Irene (Mrs)',      appointmentType: 'Admin',              status: 'Completed',    chiNumber: '450619 2837', phone: '07723 456 781', notes: 'Fit note extension requested. Off work with lower back pain following a fall at home. Physiotherapy ongoing. Two-week extension agreed.' },
  { id: 'sm-03', columnId: 'malik', type: 'appointment', startTime: '09:20', durationMins: 10, patientName: 'HARTLEY, Charles (Mr)',    appointmentType: 'Face-to-face',       status: 'Completed',    chiNumber: '871304 6152', phone: '07654 321 098', notes: 'Presenting with recurring frontal headaches for two weeks. No visual symptoms or nausea. Blood pressure normal. Likely tension headache — advised to monitor and return if worsening.' },
  { id: 'sm-04', columnId: 'malik', type: 'appointment', startTime: '09:30', durationMins: 20, patientName: 'PATEL, Susan (Mrs)',       appointmentType: 'Medication review',  status: 'Completed',    chiNumber: '629015 3874', phone: '07512 876 543', notes: 'Routine medication review. On metformin 500mg twice daily and lisinopril 5mg. Both tolerated well. Repeat bloods requested including HbA1c and renal function.' },
  { id: 'sm-05', columnId: 'malik', type: 'contact', startTime: '09:50', durationMins: 10, patientName: 'CRAWFORD, Thomas (Mr)', title: 'Follow-up call — discuss blood results', chiNumber: '261083 7492', phone: '07910 244 033', interactionStatus: 'To do', assignedTo: 'Dr Sarah Malik' },
  { id: 'sm-06', columnId: 'malik', type: 'blocked',     startTime: '10:00', durationMins: 30, blockedLabel: 'Admin / correspondence'  },
  { id: 'sm-07', columnId: 'malik', type: 'appointment', startTime: '10:30', durationMins: 10, patientName: 'HOLMES, Margaret (Mrs)',   appointmentType: 'Medication review',  status: 'In Progress',  chiNumber: '483920 1754', phone: '07832 156 490', notes: 'Due for annual medication review. Currently taking ramipril and atorvastatin. Reports occasional muscle aches since starting statin — patient wishes to discuss whether an alternative can be considered.' },
  { id: 'sm-08', columnId: 'malik', type: 'appointment', startTime: '10:40', durationMins: 10, patientName: 'CRAWFORD, Thomas (Mr)',    appointmentType: 'Follow-up',          status: 'Arrived',      chiNumber: '261083 7492', phone: '07910 244 033', notes: 'Follow-up following last month\'s chest infection. Completed course of amoxicillin. Symptoms resolved. Check recent bloods.' },
  { id: 'sm-09', columnId: 'malik', type: 'appointment', startTime: '10:50', durationMins: 10, patientName: 'FARROW, Nina (Ms)',        appointmentType: 'Asthma review',      status: 'Booked',       chiNumber: '739452 8163', phone: '07741 882 317', notes: 'Routine asthma review. PEFR diary requested at last visit. Patient reports using reliever inhaler more frequently in recent weeks, particularly in cold weather.' },
  { id: 'sm-10', columnId: 'malik', type: 'appointment', startTime: '11:00', durationMins: 10, patientName: 'ASHWORTH, Linda (Mrs)',    appointmentType: 'Face-to-face',       status: 'DNA',          chiNumber: '193507 4826', phone: '07346 890 123', notes: 'Appointment for discussion of recent smear result correspondence. Patient did not attend. Telephone contact attempted — no answer. Recall letter to be sent.' },
  { id: 'sm-11', columnId: 'malik', type: 'appointment', startTime: '11:10', durationMins: 20, patientName: 'BAINES, Christopher (Mr)', appointmentType: 'Annual review',      status: 'Booked',       chiNumber: '748261 0935', phone: '07867 012 345', notes: 'Annual chronic disease review. Patient has type 2 diabetes, hypertension, and hypercholesterolaemia. Bloods due: HbA1c, lipids, renal function, LFTs.' },
  { id: 'sm-12', columnId: 'malik', type: 'review', startTime: '11:30', durationMins: 10, patientName: 'CRAWFORD, Thomas (Mr)', title: 'Review FBC results', chiNumber: '261083 7492', interactionStatus: 'To do', assignedTo: 'Dr Sarah Malik' },
  { id: 'sm-13', columnId: 'malik', type: 'appointment', startTime: '11:40', durationMins: 20, patientName: 'NEVILLE, Patricia (Mrs)',  appointmentType: 'Mental health',      status: 'Booked',       chiNumber: '384920 6751', phone: '07478 234 567', notes: 'Ongoing mental health review. Managing moderate depression with sertraline 100mg. Discuss current effectiveness, side effects, and whether dose adjustment is appropriate.' },
  { id: 'sm-14', columnId: 'malik', type: 'blocked',     startTime: '12:00', durationMins: 60, blockedLabel: 'Lunch'                   },
  { id: 'sm-15', columnId: 'malik', type: 'appointment', startTime: '13:00', durationMins: 10, patientName: 'HARDY, Michael (Mr)',      appointmentType: 'Urgent',             status: 'Arrived',      chiNumber: '592317 8046', phone: '07523 669 410', notes: 'Walk-in urgent appointment. Patient reporting acute chest pain and shortness of breath for the past two hours. Referred in by 111. ECG required.' },
  { id: 'sm-16', columnId: 'malik', type: 'appointment', startTime: '13:10', durationMins: 20, patientName: 'SIMMONS, Carol (Mrs)',     appointmentType: "Women's health",     status: 'Booked',       chiNumber: '561803 2947', phone: '07589 456 789', notes: 'Consultation regarding irregular menstrual cycles over the past three months. Patient is 47. Discussing possible perimenopause and whether further investigation or referral is needed.' },
  { id: 'sm-17', columnId: 'malik', type: 'appointment', startTime: '13:30', durationMins: 20, patientName: 'MURRAY, David (Mr)',       appointmentType: 'Respiratory',        status: 'Running Late', chiNumber: '927146 3580', phone: '07712 678 901', notes: 'COPD review following recent exacerbation managed at home. Rescue antibiotics and steroids completed two weeks ago. Assess current lung function and review inhaler regime.' },
  { id: 'sm-18', columnId: 'malik', type: 'follow-up', startTime: '13:50', durationMins: 10, patientName: 'MORRISON, Steven (Mr)', title: 'Review medication changes', chiNumber: '673041 8295', interactionStatus: 'To do', assignedTo: 'Dr Sarah Malik' },
  { id: 'sm-19', columnId: 'malik', type: 'appointment', startTime: '14:00', durationMins: 10, patientName: 'CLARKSON, Brian (Mr)',     appointmentType: 'Face-to-face',       status: 'Booked',       chiNumber: '236874 1059', phone: '07634 890 123', notes: 'New rash on lower left leg, present for approximately one week. No known allergies. Area is red and slightly warm — concerned about possible cellulitis or dermatitis.' },
  { id: 'sm-20', columnId: 'malik', type: 'appointment', startTime: '14:10', durationMins: 20, patientName: 'WEBB, Karen (Mrs)',        appointmentType: 'Annual review',      status: 'Booked',       chiNumber: '815390 2764', phone: '07456 012 345', notes: 'Annual hypertension review. Patient on amlodipine 10mg. Bloods due. Recent home BP readings have been variable — patient to bring home monitoring diary.' },
  { id: 'sm-21', columnId: 'malik', type: 'appointment', startTime: '14:30', durationMins: 20, patientName: 'MORRISON, Steven (Mr)',    appointmentType: 'Diabetes review',    status: 'Booked',       chiNumber: '673041 8295', phone: '07378 234 567', notes: 'Diabetes review. Last HbA1c was 68 mmol/mol six months ago. Patient reports improved diet and increased physical activity. Repeat HbA1c and review current medication.' },
  { id: 'sm-22', columnId: 'malik', type: 'task', startTime: '14:50', durationMins: 10, patientName: 'FARROW, Nina (Ms)', title: 'Complete referral letter', chiNumber: '739452 8163', interactionStatus: 'To do', assignedTo: 'Dr Sarah Malik' },
  { id: 'sm-23', columnId: 'malik', type: 'blocked',     startTime: '15:00', durationMins: 30, blockedLabel: 'Clinical meeting'        },
  { id: 'sm-24', columnId: 'malik', type: 'appointment', startTime: '15:30', durationMins: 10, patientName: 'RICHARDS, Anne (Mrs)',     appointmentType: 'Admin',              status: 'Booked',       chiNumber: '294517 8630', phone: '07890 456 789', notes: 'Requesting completion of insurance medical report form. Patient to bring form. Also enquiring about travel vaccination requirements for a planned trip to Southeast Asia.' },
  { id: 'sm-25', columnId: 'malik', type: 'appointment', startTime: '15:40', durationMins: 10, patientName: 'HOLLOWAY, Frank (Mr)',     appointmentType: 'Follow-up',          status: 'Booked',       chiNumber: '758423 0196', phone: '07612 678 901', notes: 'Four-week follow-up after starting ramipril 5mg for hypertension. Check for side effects including cough. Repeat BP and renal function check as per protocol.' },
  { id: 'sm-26', columnId: 'malik', type: 'available',   startTime: '15:50', durationMins: 10 },
  { id: 'sm-27', columnId: 'malik', type: 'appointment', startTime: '16:00', durationMins: 20, patientName: 'THORNTON, Dorothy (Mrs)',  appointmentType: 'Mental health',      status: 'Booked',       chiNumber: '136894 5027', phone: '07534 890 123', notes: 'Mental health review. Patient experiencing increased anxiety following bereavement six weeks ago. Not currently on medication. Assess suitability for CBT referral.' },
  { id: 'sm-28', columnId: 'malik', type: 'appointment', startTime: '16:20', durationMins: 10, patientName: 'LAWSON, George (Mr)',      appointmentType: 'Results review',     status: 'Booked',       chiNumber: '849062 3715', phone: '07356 012 345', notes: 'Results review for bloods taken ten days ago: PSA, FBC, and LFTs. Patient seen last month with unexplained fatigue and unintentional weight loss of 4kg.' },
  { id: 'sm-29', columnId: 'malik', type: 'blocked',     startTime: '16:30', durationMins: 30, blockedLabel: 'Admin'                   },

  // ─── Dr James Reid ───────────────────────────────────────────────────────
  { id: 'jr-01', columnId: 'reid', type: 'appointment', startTime: '09:00', durationMins: 10, patientName: 'NORRIS, Robert (Mr)',     appointmentType: 'Face-to-face',      status: 'Completed',    chiNumber: '507318 9246', phone: '07923 456 780', notes: 'Presenting with lower abdominal pain and urinary frequency for three days. Urine dipstick positive. UTI confirmed — trimethoprim prescribed.' },
  { id: 'jr-02', columnId: 'reid', type: 'appointment', startTime: '09:10', durationMins: 10, patientName: 'FITZGERALD, Jean (Mrs)',  appointmentType: 'Face-to-face',      status: 'Completed',    chiNumber: '641297 0583', phone: '07845 678 901', notes: 'Requesting repeat prescription for HRT patch. Symptoms well managed. Annual review due next month. Blood pressure checked and within target.' },
  { id: 'jr-03', columnId: 'reid', type: 'appointment', startTime: '09:20', durationMins: 20, patientName: 'WHITMORE, Alan (Mr)',     appointmentType: 'Diabetes review',   status: 'Completed',    chiNumber: '872035 4619', phone: '07767 890 123', notes: 'Six-month diabetes review. HbA1c improved to 54 mmol/mol from 61. Patient has been adhering to dietary changes. Continuing metformin. Positive progress noted.' },
  { id: 'jr-04', columnId: 'reid', type: 'appointment', startTime: '09:40', durationMins: 10, patientName: 'OKAFOR, Brenda (Mrs)',    appointmentType: 'Follow-up',         status: 'Completed',    chiNumber: '319760 2845', phone: '07589 012 345', notes: 'Follow-up after referral to rheumatology for joint pain. Letter received — inflammatory arthritis suspected. Naproxen 500mg prescribed pending specialist review.' },
  { id: 'jr-05', columnId: 'reid', type: 'available',   startTime: '09:50', durationMins: 10 },
  { id: 'jr-06', columnId: 'reid', type: 'appointment', startTime: '10:00', durationMins: 10, patientName: 'HADLEY, Eric (Mr)',       appointmentType: 'Routine',           status: 'Cancelled',    chiNumber: '428591 6073', phone: '07411 234 567', notes: 'Routine review of ongoing back pain management. Patient cancelled same day. Currently on ibuprofen PRN. Appointment to be rebooked.' },
  { id: 'jr-07', columnId: 'reid', type: 'appointment', startTime: '10:10', durationMins: 20, patientName: 'MACINTYRE, Fiona (Ms)',   appointmentType: 'Asthma review',     status: 'Arrived',      chiNumber: '176493 0528', phone: '07304 881 245', notes: 'Six-month asthma review. Well-controlled on current regime. Reports increasing exercise-induced symptoms when running. Wishes to discuss Montelukast as an add-on therapy. PEFR recorded at last visit 440 L/min.' },
  { id: 'jr-08', columnId: 'reid', type: 'appointment', startTime: '10:30', durationMins: 10, patientName: 'STANTON, Harry (Mr)',     appointmentType: 'Face-to-face',      status: 'In Progress',  chiNumber: '847036 2915', phone: '07689 103 856', notes: 'New complaint. Patient experiencing persistent lower back pain for three weeks following a lifting injury at work. Requesting physiotherapy referral and fit note.' },
  { id: 'jr-09', columnId: 'reid', type: 'appointment', startTime: '10:40', durationMins: 20, patientName: 'THORNTON, Julie (Mrs)',   appointmentType: 'Medication review', status: 'Booked',       chiNumber: '965148 3027', phone: '07533 456 789', notes: 'Annual medication review. Patient on levothyroxine 75mcg and citalopram 20mg. TSH check due. Discuss mood management and whether citalopram dose needs review.' },
  { id: 'jr-10', columnId: 'reid', type: 'appointment', startTime: '11:00', durationMins: 10, patientName: 'GALLAGHER, Lewis (Mr)',   appointmentType: 'Mental health',     status: 'Booked',       chiNumber: '203847 5691', phone: '07455 678 901', notes: 'Mental health review following referral from emergency department three months ago. Patient was assessed for self-harm. Currently under CMHT. GP review to coordinate care.' },
  { id: 'jr-11', columnId: 'reid', type: 'blocked',     startTime: '11:10', durationMins: 30, blockedLabel: 'Home visits'            },
  { id: 'jr-12', columnId: 'reid', type: 'appointment', startTime: '11:40', durationMins: 20, patientName: 'POTTS, Rachel (Ms)',      appointmentType: "Women's health",    status: 'Booked',       chiNumber: '716492 3058', phone: '07677 890 123', notes: 'Contraception review. Patient wishes to discuss options following cessation of the combined pill due to migraines. Interested in progesterone-only or long-acting reversible contraception.' },
  { id: 'jr-13', columnId: 'reid', type: 'blocked',     startTime: '12:00', durationMins: 60, blockedLabel: 'Lunch'                  },
  { id: 'jr-14', columnId: 'reid', type: 'appointment', startTime: '13:00', durationMins: 20, patientName: 'CLARK, Andrew (Mr)',      appointmentType: 'Respiratory',       status: 'Booked',       chiNumber: '583027 1964', phone: '07799 012 345', notes: 'Asthma review with follow-up from secondary care. Patient was admitted last winter with severe exacerbation. Now on ICS/LABA combination. Check PEFR and inhaler technique.' },
  { id: 'jr-15', columnId: 'reid', type: 'appointment', startTime: '13:20', durationMins: 10, patientName: 'PRYCE, Olivia (Mrs)',     appointmentType: 'Routine',           status: 'DNA',          chiNumber: '364710 8295', phone: '07621 234 567', notes: 'Booked for discussion of persistent bloating and change in bowel habit over six weeks. Patient did not attend. Symptoms may warrant further investigation if ongoing.' },
  { id: 'jr-16', columnId: 'reid', type: 'appointment', startTime: '13:30', durationMins: 20, patientName: 'HASTINGS, Clive (Mr)',    appointmentType: 'Follow-up',         status: 'Running Late', chiNumber: '841593 2076', phone: '07743 456 789', notes: 'Follow-up after cardioversion two weeks ago for atrial fibrillation. Currently on apixaban and bisoprolol. Check heart rate, rhythm, and symptom control.' },
  { id: 'jr-17', columnId: 'reid', type: 'available',   startTime: '13:50', durationMins: 10 },
  { id: 'jr-18', columnId: 'reid', type: 'appointment', startTime: '14:00', durationMins: 30, patientName: 'BARKER, Wendy (Mrs)',     appointmentType: 'Annual review',     status: 'Booked',       chiNumber: '157364 8902', phone: '07865 678 901', notes: 'Annual review for multiple long-term conditions: COPD, atrial fibrillation, and CKD stage 3. Bloods due. Review inhaler technique, anticoagulation, and renal function trend.' },
  { id: 'jr-19', columnId: 'reid', type: 'available',   startTime: '14:30', durationMins: 10 },
  { id: 'jr-20', columnId: 'reid', type: 'appointment', startTime: '14:40', durationMins: 20, patientName: 'BRENT, Nicholas (Mr)',    appointmentType: 'Hypertension',      status: 'Booked',       chiNumber: '492071 6358', phone: '07387 890 123', notes: 'Hypertension review. On amlodipine 5mg and losartan 50mg. Recent 24-hour BP monitor shows readings still elevated. Discuss dose escalation or adding a further agent.' },
  { id: 'jr-21', columnId: 'reid', type: 'blocked',     startTime: '15:00', durationMins: 30, blockedLabel: 'Clinical meeting'       },
  { id: 'jr-22', columnId: 'reid', type: 'appointment', startTime: '15:30', durationMins: 10, patientName: 'TURNBULL, Sarah (Ms)',    appointmentType: 'Face-to-face',      status: 'Booked',       chiNumber: '726839 0415', phone: '07509 012 345', notes: 'New presentation of joint pain affecting both hands for six weeks. Morning stiffness lasting over an hour. Requesting inflammatory markers and rheumatology referral.' },
  { id: 'jr-23', columnId: 'reid', type: 'appointment', startTime: '15:40', durationMins: 20, patientName: 'WALSH, Dennis (Mr)',      appointmentType: 'Respiratory',       status: 'Booked',       chiNumber: '358612 7049', phone: '07431 234 567', notes: 'COPD and bronchiectasis review. Recently discharged from community respiratory programme. Review self-management plan and consider pulmonary rehabilitation referral.' },
  { id: 'jr-24', columnId: 'reid', type: 'available',   startTime: '16:00', durationMins: 10 },
  { id: 'jr-25', columnId: 'reid', type: 'appointment', startTime: '16:10', durationMins: 20, patientName: 'MERCER, Pauline (Mrs)',   appointmentType: 'Mental health',     status: 'Booked',       chiNumber: '814275 6930', phone: '07653 456 789', notes: 'Mental health review. Patient on mirtazapine 30mg for severe depression following bereavement. Significant improvement over the past two months. Discuss gradual dose reduction.' },
  { id: 'jr-26', columnId: 'reid', type: 'blocked',     startTime: '16:30', durationMins: 30, blockedLabel: 'Admin'                  },

  // ─── Amy Wilson — Practice Nurse ─────────────────────────────────────────
  { id: 'aw-01', columnId: 'wilson', type: 'appointment', startTime: '09:00', durationMins: 15, patientName: 'SUTHERLAND, Gail (Ms)',  appointmentType: "Women's health",    status: 'Completed',    chiNumber: '264509 1837', phone: '07875 678 901', notes: 'Cervical smear taken. Patient last screened five years ago. No concerns raised at time of test. Results to be sent by post within two weeks.' },
  { id: 'aw-02', columnId: 'wilson', type: 'appointment', startTime: '09:15', durationMins: 15, patientName: 'YATES, Ian (Mr)',         appointmentType: 'Injection',         status: 'Completed',    chiNumber: '731840 5296', phone: '07697 890 123', notes: 'B12 injection administered — hydroxocobalamin 1mg IM. Patient is on 12-weekly schedule. No adverse reaction. Next due in three months.' },
  { id: 'aw-03', columnId: 'wilson', type: 'appointment', startTime: '09:30', durationMins: 15, patientName: 'CHAN, Beverley (Mrs)',    appointmentType: 'Wound care',        status: 'Completed',    chiNumber: '456712 9083', phone: '07519 012 345', notes: 'Dressing change to chronic venous leg ulcer on left lower leg. Wound clean, no signs of infection. Granulating well. Continue with compression bandaging and weekly review.' },
  { id: 'aw-04', columnId: 'wilson', type: 'available',   startTime: '09:45', durationMins: 15 },
  { id: 'aw-05', columnId: 'wilson', type: 'appointment', startTime: '10:00', durationMins: 30, patientName: 'FERNANDEZ, Robin (Mr)',   appointmentType: 'Diabetes',          status: 'Completed',    chiNumber: '893024 7651', phone: '07341 234 567', notes: 'Diabetic annual footcare review. No active foot problems identified. Monofilament sensation intact bilaterally. Advised to continue daily foot inspection and appropriate footwear.' },
  { id: 'aw-06', columnId: 'wilson', type: 'appointment', startTime: '10:30', durationMins: 15, patientName: 'HEWITT, Sandra (Mrs)',    appointmentType: 'Wound care',        status: 'In Progress',  chiNumber: '114758 3290', phone: '07255 930 481', notes: 'Re-dressing of surgical wound following knee replacement. Check for signs of infection. Patient reports wound has been uncomfortable overnight.' },
  { id: 'aw-07', columnId: 'wilson', type: 'appointment', startTime: '10:45', durationMins: 15, patientName: 'BUTCHER, Owen (Mr)',      appointmentType: 'Vaccination',       status: 'Arrived',      chiNumber: '628941 0375', phone: '07456 724 198', notes: 'Shingles vaccination, second dose. No adverse reactions reported after first dose six weeks ago.' },
  { id: 'aw-08', columnId: 'wilson', type: 'appointment', startTime: '11:00', durationMins: 15, patientName: 'HOPKINS, Tracey (Mrs)',   appointmentType: "Women's health",    status: 'Booked',       chiNumber: '570391 2846', phone: '07763 456 789', notes: 'Postnatal check at six weeks. Patient delivered healthy baby girl. Discussing contraception options and infant feeding. Edinburgh postnatal depression score to be completed.' },
  { id: 'aw-09', columnId: 'wilson', type: 'appointment', startTime: '11:15', durationMins: 15, patientName: 'LONG, Barry (Mr)',        appointmentType: 'Vaccination',       status: 'DNA',          chiNumber: '218647 5039', phone: '07585 678 901', notes: 'Flu and pneumococcal vaccination booked. Patient is 70 and in clinical risk group. Did not attend. Recall letter to be sent.' },
  { id: 'aw-10', columnId: 'wilson', type: 'blocked',     startTime: '11:30', durationMins: 30, blockedLabel: 'Protected learning time' },
  { id: 'aw-11', columnId: 'wilson', type: 'blocked',     startTime: '12:00', durationMins: 60, blockedLabel: 'Lunch'                  },
  { id: 'aw-12', columnId: 'wilson', type: 'appointment', startTime: '13:00', durationMins: 15, patientName: 'DEWHURST, Gillian (Mrs)', appointmentType: 'Asthma review',     status: 'Booked',       chiNumber: '647190 3825', phone: '07407 890 123', notes: 'Annual asthma review. Patient on salbutamol PRN and budesonide 200mcg twice daily. Stepped up at last review. Check PEFR, assess symptom control, and review inhaler technique.' },
  { id: 'aw-13', columnId: 'wilson', type: 'appointment', startTime: '13:15', durationMins: 15, patientName: 'FORSYTH, Alec (Mr)',      appointmentType: 'ECG',               status: 'Booked',       chiNumber: '329056 8714', phone: '07929 012 345', notes: 'Resting 12-lead ECG requested by Dr Reid following a recent episode of palpitations lasting approximately 20 minutes. Patient has no prior cardiac history.' },
  { id: 'aw-14', columnId: 'wilson', type: 'appointment', startTime: '13:30', durationMins: 30, patientName: 'ROWLEY, Helen (Mrs)',     appointmentType: 'New patient',       status: 'Booked',       chiNumber: '785413 2960', phone: '07751 234 567', notes: 'New patient registration consultation. Recently moved to the area. History of rheumatoid arthritis managed with methotrexate. Needs new patient bloods and medication review.' },
  { id: 'aw-15', columnId: 'wilson', type: 'appointment', startTime: '14:00', durationMins: 15, patientName: 'MARSDEN, Colin (Mr)',     appointmentType: 'BP check',          status: 'Booked',       chiNumber: '412867 5039', phone: '07473 456 789', notes: 'BP check. Patient recently started on bisoprolol 2.5mg for newly diagnosed hypertension. Checking response to medication and tolerance.' },
  { id: 'aw-16', columnId: 'wilson', type: 'appointment', startTime: '14:15', durationMins: 15, patientName: 'OLSEN, Jackie (Mrs)',     appointmentType: 'Vaccination',       status: 'Booked',       chiNumber: '956234 8107', phone: '07695 678 901', notes: 'Pertussis booster vaccination at 28 weeks of pregnancy. Patient is pregnant with second child. No known contraindications identified at booking.' },
  { id: 'aw-17', columnId: 'wilson', type: 'blocked',     startTime: '14:30', durationMins: 30, blockedLabel: 'Admin / notes'          },
  { id: 'aw-18', columnId: 'wilson', type: 'appointment', startTime: '15:00', durationMins: 15, patientName: 'HAMMOND, Victor (Mr)',    appointmentType: 'Ear care',          status: 'Booked',       chiNumber: '163720 9485', phone: '07517 890 123', notes: 'Ear irrigation for bilateral wax impaction. Patient reports reduced hearing for three weeks and sensation of fullness. Sodium bicarbonate drops used for five days.' },
  { id: 'aw-19', columnId: 'wilson', type: 'appointment', startTime: '15:15', durationMins: 15, patientName: 'PROCTOR, Natalie (Ms)',   appointmentType: "Women's health",    status: 'Running Late', chiNumber: '837495 0612', phone: '07739 012 345', notes: 'IUD fitting. Patient has had full counselling and has consented. Last menstrual period confirmed. No contraindications identified at pre-fitting check two weeks ago.' },
  { id: 'aw-20', columnId: 'wilson', type: 'appointment', startTime: '15:30', durationMins: 15, patientName: 'WHEATLEY, Ray (Mr)',      appointmentType: 'Blood test',        status: 'Booked',       chiNumber: '274618 5390', phone: '07461 234 567', notes: 'Fasting blood test: lipid profile, fasting glucose, and LFTs. Patient has new family history of cardiovascular disease following father\'s recent heart attack.' },
  { id: 'aw-21', columnId: 'wilson', type: 'available',   startTime: '15:45', durationMins: 15 },
  { id: 'aw-22', columnId: 'wilson', type: 'appointment', startTime: '16:00', durationMins: 30, patientName: 'SOMMERS, Elaine (Mrs)',   appointmentType: 'Respiratory',       status: 'Booked',       chiNumber: '619382 7045', phone: '07683 456 789', notes: 'Asthma and allergy review. Patient recently attended A&E following acute asthma attack. Currently on MART regime. Review trigger factors, technique, and emergency action plan.' },
  { id: 'aw-23', columnId: 'wilson', type: 'blocked',     startTime: '16:30', durationMins: 30, blockedLabel: 'Catch-up admin'         },

  // ─── Mark Douglas — Healthcare Assistant ─────────────────────────────────
  { id: 'md-01', columnId: 'douglas', type: 'appointment', startTime: '09:00', durationMins: 15, patientName: 'SHERWOOD, Paul (Mr)',    appointmentType: 'BP check',          status: 'Completed',    chiNumber: '831046 2759', phone: '07905 678 901', notes: 'BP monitoring for newly diagnosed hypertension. Reading today 142/88. Lifestyle advice given. Repeat in two weeks — start medication if readings remain elevated.' },
  { id: 'md-02', columnId: 'douglas', type: 'appointment', startTime: '09:15', durationMins: 15, patientName: 'GRIFFITHS, Molly (Ms)', appointmentType: 'Health check',      status: 'Completed',    chiNumber: '475203 8916', phone: '07727 890 123', notes: 'NHS health check at age 45. Cholesterol 5.2, BP 124/78, BMI 24, non-smoker. Low cardiovascular risk score. Healthy lifestyle advice given. No further action required.' },
  { id: 'md-03', columnId: 'douglas', type: 'appointment', startTime: '09:30', durationMins: 15, patientName: 'HOLT, Norman (Mr)',      appointmentType: 'Urinalysis',        status: 'Completed',    chiNumber: '692817 4053', phone: '07549 012 345', notes: 'Urine sample collected for culture and sensitivity as part of CKD monitoring. Patient on ACE inhibitor. Results to be reviewed by GP.' },
  { id: 'md-04', columnId: 'douglas', type: 'appointment', startTime: '09:45', durationMins: 15, patientName: 'ATKINS, Deborah (Mrs)', appointmentType: 'ECG',               status: 'Completed',    chiNumber: '348592 0167', phone: '07371 234 567', notes: 'ECG performed following referral from Dr Malik. Patient had episode of chest tightness on exertion. ECG showed normal sinus rhythm. Results forwarded to GP.' },
  { id: 'md-05', columnId: 'douglas', type: 'appointment', startTime: '10:00', durationMins: 15, patientName: 'TUCKER, Glenn (Mr)',     appointmentType: 'BP check',          status: 'In Progress',  chiNumber: '305817 4629', phone: '07812 490 637', notes: 'Hypertension monitoring. Patient started on amlodipine 5mg three months ago. Check BP both arms. Review home readings diary.' },
  { id: 'md-06', columnId: 'douglas', type: 'appointment', startTime: '10:15', durationMins: 15, patientName: 'FOX, Harriet (Ms)',      appointmentType: 'Health check',      status: 'Arrived',      chiNumber: '419062 5837', phone: '07673 318 024', notes: 'NHS health check. First-time attendee, age 47. Full check including cholesterol, BP, BMI, and lifestyle review. Family history of type 2 diabetes.' },
  { id: 'md-07', columnId: 'douglas', type: 'appointment', startTime: '10:30', durationMins: 15, patientName: 'BALDWIN, Scott (Mr)',    appointmentType: 'Pre-op',            status: 'Booked',       chiNumber: '716083 4592', phone: '07793 456 789', notes: 'Pre-operative assessment for elective inguinal hernia repair scheduled in three weeks. Bloods, ECG, and MRSA swabs required. Confirm no medication changes since booking.' },
  { id: 'md-08', columnId: 'douglas', type: 'appointment', startTime: '10:45', durationMins: 15, patientName: 'COOK, Mandy (Ms)',       appointmentType: 'Admin',             status: 'Booked',       chiNumber: '253867 1490', phone: '07415 678 901', notes: 'Height, weight, and BMI measurement requested by Dr Wilson as part of structured weight management plan. Patient is enrolled in the NHS weight management programme.' },
  { id: 'md-09', columnId: 'douglas', type: 'blocked',     startTime: '11:00', durationMins: 30, blockedLabel: 'Stock check / supplies' },
  { id: 'md-10', columnId: 'douglas', type: 'blocked',     startTime: '11:30', durationMins: 30, blockedLabel: 'Training'              },
  { id: 'md-11', columnId: 'douglas', type: 'blocked',     startTime: '12:00', durationMins: 60, blockedLabel: 'Lunch'                 },
  { id: 'md-12', columnId: 'douglas', type: 'appointment', startTime: '13:00', durationMins: 15, patientName: 'QUINN, Lynda (Mrs)',     appointmentType: 'Admin',             status: 'Booked',       chiNumber: '980312 6745', phone: '07637 890 123', notes: 'INR check. Patient on warfarin for mechanical heart valve. Target INR 2.5–3.5. Last result was 2.8 three weeks ago. Regular monitoring as per clinic protocol.' },
  { id: 'md-13', columnId: 'douglas', type: 'appointment', startTime: '13:15', durationMins: 15, patientName: 'PARK, Oscar (Mr)',       appointmentType: 'BP check',          status: 'DNA',          chiNumber: '534079 8126', phone: '07459 012 345', notes: 'BP monitoring follow-up after starting amlodipine 5mg six weeks ago. Patient did not attend. Medication running low — reception to chase urgently and rebook.' },
  { id: 'md-14', columnId: 'douglas', type: 'appointment', startTime: '13:30', durationMins: 15, patientName: 'MILES, Vera (Mrs)',      appointmentType: 'Urinalysis',        status: 'Booked',       chiNumber: '867241 5093', phone: '07381 234 567', notes: 'Urine dipstick and MSU for recurrent UTI investigation. Third UTI this year. GP has requested urine for culture. Possible referral for cystoscopy if positive again.' },
  { id: 'md-15', columnId: 'douglas', type: 'appointment', startTime: '13:45', durationMins: 15, patientName: 'ABBOTT, Cyril (Mr)',     appointmentType: 'Health check',      status: 'Booked',       chiNumber: '123984 6750', phone: '07603 456 789', notes: 'NHS health check at age 65. Assess cardiovascular risk, lipids, blood glucose, BP, and BMI. Lifestyle questionnaire to be completed. Family history of diabetes.' },
  { id: 'md-16', columnId: 'douglas', type: 'blocked',     startTime: '14:00', durationMins: 60, blockedLabel: 'Administration & filing' },
  { id: 'md-17', columnId: 'douglas', type: 'appointment', startTime: '15:00', durationMins: 15, patientName: 'PALMER, Doris (Mrs)',    appointmentType: 'Health check',      status: 'Booked',       chiNumber: '760415 8239', phone: '07825 678 901', notes: 'NHS health check with frailty assessment, age 72. Standard checks alongside fall risk review following a trip at home last month. Review current medication list.' },
  { id: 'md-18', columnId: 'douglas', type: 'available',   startTime: '15:15', durationMins: 15 },
  { id: 'md-19', columnId: 'douglas', type: 'appointment', startTime: '15:30', durationMins: 15, patientName: 'SIMMONS, Frank (Mr)',    appointmentType: 'Urinalysis',        status: 'Booked',       chiNumber: '437826 1095', phone: '07547 890 123', notes: 'Urine sample for routine diabetic monitoring. HbA1c and renal function bloods also requested by Dr Malik. Urine albumin:creatinine ratio included.' },
  { id: 'md-20', columnId: 'douglas', type: 'appointment', startTime: '15:45', durationMins: 15, patientName: 'WALTON, Grace (Mrs)',    appointmentType: 'Pre-op',            status: 'Booked',       chiNumber: '892163 5047', phone: '07369 012 345', notes: 'Pre-operative assessment for elective right eye cataract surgery in two weeks. Bloods and ECG required. Patient on aspirin — awaiting surgical team guidance on peri-operative management.' },
  { id: 'md-21', columnId: 'douglas', type: 'blocked',     startTime: '16:00', durationMins: 30, blockedLabel: 'Equipment prep'        },
  { id: 'md-22', columnId: 'douglas', type: 'blocked',     startTime: '16:30', durationMins: 30, blockedLabel: 'End of day admin'      },

  // ─── Phlebotomy Clinic ────────────────────────────────────────────────────
  { id: 'ph-01', columnId: 'phlebotomy', type: 'appointment', startTime: '09:00', durationMins: 10, patientName: 'BROWNE, Millicent (Mrs)', appointmentType: 'Blood test', status: 'Completed',    chiNumber: '318740 6295', phone: '07891 012 340', notes: 'Annual diabetic monitoring bloods: HbA1c, lipids, renal function, and LFTs. Fasting sample. Requested by Diabetes Clinic.' },
  { id: 'ph-02', columnId: 'phlebotomy', type: 'appointment', startTime: '09:10', durationMins: 10, patientName: 'CASEY, Tom (Mr)',          appointmentType: 'Blood test', status: 'Completed',    chiNumber: '765092 3481', phone: '07713 234 561', notes: 'TFTs and FBC. Requested by Dr Reid following complaints of fatigue and weight gain over the past two months.' },
  { id: 'ph-03', columnId: 'phlebotomy', type: 'appointment', startTime: '09:20', durationMins: 10, patientName: 'GIBSON, Freda (Mrs)',      appointmentType: 'Blood test', status: 'Completed',    chiNumber: '423817 5096', phone: '07535 456 782', notes: 'INR check for patient on warfarin. Target INR 2.0–3.0 for atrial fibrillation. Last result 2.4. Regular monitoring as per protocol.' },
  { id: 'ph-04', columnId: 'phlebotomy', type: 'appointment', startTime: '09:30', durationMins: 10, patientName: 'BARNETT, Hugh (Mr)',       appointmentType: 'Blood test', status: 'Completed',    chiNumber: '981264 5037', phone: '07357 678 903', notes: 'PSA and FBC. Patient has history of prostate cancer in remission. Annual monitoring as per oncology guidance. Requested by Dr Malik.' },
  { id: 'ph-05', columnId: 'phlebotomy', type: 'appointment', startTime: '09:40', durationMins: 10, patientName: 'CRISP, Stella (Mrs)',      appointmentType: 'Blood test', status: 'Completed',    chiNumber: '647039 2815', phone: '07979 890 124', notes: 'Pre-operative bloods for elective knee replacement. Requested by orthopaedic team: FBC, U&E, coagulation, and group and save.' },
  { id: 'ph-06', columnId: 'phlebotomy', type: 'available',   startTime: '09:50', durationMins: 10 },
  { id: 'ph-07', columnId: 'phlebotomy', type: 'appointment', startTime: '10:00', durationMins: 10, patientName: 'BANKS, Walter (Mr)',       appointmentType: 'Blood test', status: 'Completed',    chiNumber: '205473 8961', phone: '07801 012 345', notes: 'Annual renal profile and FBC for CKD monitoring. Patient on ACE inhibitor. Requested by Dr Reid.' },
  { id: 'ph-08', columnId: 'phlebotomy', type: 'appointment', startTime: '10:10', durationMins: 10, patientName: 'JENNINGS, Nora (Mrs)',     appointmentType: 'Blood test', status: 'Completed',    chiNumber: '863520 1749', phone: '07623 234 566', notes: 'Fasting lipid profile and HbA1c. Patient newly diagnosed with type 2 diabetes at last GP visit. Baseline bloods requested by Dr Malik.' },
  { id: 'ph-09', columnId: 'phlebotomy', type: 'appointment', startTime: '10:20', durationMins: 10, patientName: 'WEBB, Marcus (Mr)',        appointmentType: 'Blood test', status: 'In Progress',  chiNumber: '531986 4072', phone: '07445 456 787', notes: 'LFTs, FBC, and vitamin D. Patient reports fatigue and muscle aches. On atorvastatin — creatine kinase also requested to investigate possible myopathy.' },
  { id: 'ph-10', columnId: 'phlebotomy', type: 'appointment', startTime: '10:30', durationMins: 10, patientName: 'HART, Cynthia (Mrs)',      appointmentType: 'Blood test', status: 'Arrived',      chiNumber: '174803 6295', phone: '07967 678 908', notes: 'Fasting bloods for annual medication review: HbA1c, lipid profile, and renal function. Patient on metformin and a statin. Last HbA1c 58 mmol/mol.' },
  { id: 'ph-11', columnId: 'phlebotomy', type: 'appointment', startTime: '10:40', durationMins: 10, patientName: 'PLATT, Stanley (Mr)',      appointmentType: 'Blood test', status: 'Booked',       chiNumber: '728345 9016', phone: '07789 890 129', notes: 'TFTs and ferritin. Requested by Dr Wilson. Patient on levothyroxine — checking TSH is in range. Tiredness reported at last consultation.' },
  { id: 'ph-12', columnId: 'phlebotomy', type: 'appointment', startTime: '10:50', durationMins: 10, patientName: 'LYNCH, Marjorie (Mrs)',    appointmentType: 'Blood test', status: 'Booked',       chiNumber: '596271 8043', phone: '07511 012 340', notes: 'Pre-op bloods for hip replacement surgery next month. Requested by orthopaedic team: FBC, U&E, clotting screen, and group and save.' },
  { id: 'ph-13', columnId: 'phlebotomy', type: 'appointment', startTime: '11:00', durationMins: 10, patientName: 'HORTON, Derek (Mr)',       appointmentType: 'Blood test', status: 'Booked',       chiNumber: '342690 5817', phone: '07433 234 561', notes: 'DMARD monitoring for rheumatoid arthritis. Patient on methotrexate — monthly FBC and LFTs as per protocol. Requested by rheumatology.' },
  { id: 'ph-14', columnId: 'phlebotomy', type: 'appointment', startTime: '11:10', durationMins: 10, patientName: 'SANDERSON, Rosie (Ms)',    appointmentType: 'Blood test', status: 'DNA',          chiNumber: '879014 3625', phone: '07855 456 782', notes: 'Routine FBC and iron studies. Patient is 28 weeks pregnant. Did not attend — midwife team to be notified and appointment rebooked urgently.' },
  { id: 'ph-15', columnId: 'phlebotomy', type: 'appointment', startTime: '11:20', durationMins: 10, patientName: 'WHITFIELD, Len (Mr)',      appointmentType: 'Blood test', status: 'Booked',       chiNumber: '413567 2890', phone: '07677 678 903', notes: 'Annual bloods for hypertension monitoring: U&E and electrolytes. Patient on lisinopril and bendroflumethiazide. Requested by Dr Reid.' },
  { id: 'ph-16', columnId: 'phlebotomy', type: 'available',   startTime: '11:30', durationMins: 10 },
  { id: 'ph-17', columnId: 'phlebotomy', type: 'appointment', startTime: '11:40', durationMins: 10, patientName: 'CARROLL, Agnes (Mrs)',     appointmentType: 'Blood test', status: 'Booked',       chiNumber: '650289 7134', phone: '07399 890 124', notes: 'B12, folate, FBC, and iron studies. Patient is vegetarian and reports progressive fatigue and pins and needles in hands. Requested by Dr Malik.' },
  { id: 'ph-18', columnId: 'phlebotomy', type: 'appointment', startTime: '11:50', durationMins: 10, patientName: 'PERKINS, Roy (Mr)',        appointmentType: 'Blood test', status: 'Booked',       chiNumber: '237845 6190', phone: '07821 012 345', notes: 'Fasting glucose and HbA1c. Elevated fasting glucose identified at health check last month. Requested by Dr Reid to confirm or exclude diabetes.' },
  { id: 'ph-19', columnId: 'phlebotomy', type: 'blocked',     startTime: '12:00', durationMins: 60, blockedLabel: 'Lunch / centrifuge processing' },
  { id: 'ph-20', columnId: 'phlebotomy', type: 'appointment', startTime: '13:00', durationMins: 10, patientName: 'CHAMBERLAIN, Edith (Mrs)', appointmentType: 'Blood test', status: 'Booked',       chiNumber: '794062 3815', phone: '07543 234 566', notes: 'Heart failure monitoring bloods: U&E, renal function, and BNP. Patient on furosemide and ramipril. Requested by cardiology and Dr Malik.' },
  { id: 'ph-21', columnId: 'phlebotomy', type: 'appointment', startTime: '13:10', durationMins: 10, patientName: 'DRUMMOND, Angus (Mr)',     appointmentType: 'Blood test', status: 'Booked',       chiNumber: '461837 5029', phone: '07365 456 787', notes: 'Monitoring bloods for gout management: uric acid and renal function. Patient recently started on allopurinol 100mg. Requested by Dr Reid.' },
  { id: 'ph-22', columnId: 'phlebotomy', type: 'appointment', startTime: '13:20', durationMins: 10, patientName: 'CHAPMAN, Daisy (Ms)',      appointmentType: 'Blood test', status: 'Booked',       chiNumber: '328590 7146', phone: '07987 678 908', notes: 'FBC and ferritin for investigation of heavy menstrual bleeding. Patient awaiting gynaecology appointment. Requested by Dr Wilson.' },
  { id: 'ph-23', columnId: 'phlebotomy', type: 'appointment', startTime: '13:30', durationMins: 10, patientName: 'ROSS, Frederick (Mr)',     appointmentType: 'Blood test', status: 'Booked',       chiNumber: '915047 2863', phone: '07709 890 129', notes: 'Annual DMARD monitoring for patient on hydroxychloroquine for lupus. FBC and LFTs as per protocol. Requested by rheumatology.' },
  { id: 'ph-24', columnId: 'phlebotomy', type: 'appointment', startTime: '13:40', durationMins: 10, patientName: 'ELLISON, Violet (Mrs)',    appointmentType: 'Blood test', status: 'Booked',       chiNumber: '576213 9084', phone: '07531 012 340', notes: 'Fasting lipid profile and glucose. Family history of type 2 diabetes — patient\'s mother recently diagnosed. Cardiovascular risk assessment. Requested by Dr Malik.' },
  { id: 'ph-25', columnId: 'phlebotomy', type: 'appointment', startTime: '13:50', durationMins: 10, patientName: 'PAYNE, Archie (Mr)',       appointmentType: 'Blood test', status: 'Booked',       chiNumber: '243896 0751', phone: '07453 234 561', notes: 'LFTs and renal function. Patient started on amiodarone for cardiac arrhythmia three months ago. Monitoring as per cardiology protocol.' },
  { id: 'ph-26', columnId: 'phlebotomy', type: 'appointment', startTime: '14:00', durationMins: 10, patientName: 'NASH, Lilian (Mrs)',       appointmentType: 'Blood test', status: 'Booked',       chiNumber: '860134 7295', phone: '07875 456 782', notes: 'TFTs for hypothyroidism management. Patient on levothyroxine 100mcg — recent dose increase after TSH was 7.2. Three-month recheck requested by Dr Reid.' },
  { id: 'ph-27', columnId: 'phlebotomy', type: 'appointment', startTime: '14:10', durationMins: 10, patientName: 'POWELL, Sidney (Mr)',      appointmentType: 'Blood test', status: 'Booked',       chiNumber: '427581 6039', phone: '07597 678 903', notes: 'FBC and CRP for investigation of unexplained weight loss and fatigue. Vitamin B12 and folate also included. Requested by Dr Malik following recent consultation.' },
  { id: 'ph-28', columnId: 'phlebotomy', type: 'appointment', startTime: '14:20', durationMins: 10, patientName: 'VERNON, Hilda (Mrs)',      appointmentType: 'Blood test', status: 'Running Late', chiNumber: '794263 0518', phone: '07319 890 124', notes: 'HbA1c and renal profile for annual diabetes review. Patient has CKD stage 3 alongside type 2 diabetes. eGFR trend important for medication review.' },
  { id: 'ph-29', columnId: 'phlebotomy', type: 'available',   startTime: '14:30', durationMins: 10 },
  { id: 'ph-30', columnId: 'phlebotomy', type: 'appointment', startTime: '14:40', durationMins: 10, patientName: 'BURTON, Cecil (Mr)',       appointmentType: 'Blood test', status: 'Booked',       chiNumber: '651079 3842', phone: '07841 012 345', notes: 'Anti-TNF monitoring for patient on adalimumab for psoriatic arthritis. FBC and LFTs monthly as per DMARD monitoring schedule. Requested by rheumatology.' },
  { id: 'ph-31', columnId: 'phlebotomy', type: 'appointment', startTime: '14:50', durationMins: 10, patientName: 'SUTTON, Ida (Mrs)',        appointmentType: 'Blood test', status: 'Booked',       chiNumber: '318742 6095', phone: '07763 234 566', notes: 'Calcium, phosphate, and PTH for long-term vitamin D deficiency management. Patient on supplementation. Requested by Dr Wilson.' },
  { id: 'ph-32', columnId: 'phlebotomy', type: 'blocked',     startTime: '15:00', durationMins: 60, blockedLabel: 'Batch processing'       },
  { id: 'ph-33', columnId: 'phlebotomy', type: 'appointment', startTime: '16:00', durationMins: 10, patientName: 'HARTLEY, Alice (Mrs)',     appointmentType: 'Blood test', status: 'Booked',       chiNumber: '985461 2073', phone: '07485 456 787', notes: 'FBC and blood cultures. Patient attended A&E last week with fever. Discharged with GP follow-up advice. Now presenting with ongoing symptoms — urgent request.' },
  { id: 'ph-34', columnId: 'phlebotomy', type: 'appointment', startTime: '16:10', durationMins: 10, patientName: 'WESTON, Percy (Mr)',       appointmentType: 'Blood test', status: 'Booked',       chiNumber: '742016 5839', phone: '07607 678 908', notes: 'Annual monitoring for polycythaemia vera: FBC with differential. Patient managed with venesection and aspirin. Requested by haematology via GP.' },
  { id: 'ph-35', columnId: 'phlebotomy', type: 'appointment', startTime: '16:20', durationMins: 10, patientName: 'BOOTH, Ethel (Mrs)',       appointmentType: 'Blood test', status: 'Booked',       chiNumber: '529384 1760', phone: '07929 890 129', notes: 'Routine monitoring for CKD stage 4: U&E, eGFR, FBC, and phosphate. Patient on phosphate binder. Results to be shared with renal unit.' },
  { id: 'ph-36', columnId: 'phlebotomy', type: 'blocked',     startTime: '16:30', durationMins: 30, blockedLabel: 'End of day processing'  },

  // ─── Diabetes Clinic ──────────────────────────────────────────────────────
  { id: 'dc-01', columnId: 'diabetes', type: 'appointment', startTime: '09:00', durationMins: 30, patientName: 'STAFFORD, Eleanor (Mrs)', appointmentType: 'Diabetes review',    status: 'Completed',    chiNumber: '183750 2946', phone: '07851 012 340', notes: 'Six-month diabetes review. HbA1c 62 mmol/mol, improved from 71. Patient adhering to dietary changes. Linagliptin dose increase discussed. Review in six months.' },
  { id: 'dc-02', columnId: 'diabetes', type: 'appointment', startTime: '09:30', durationMins: 30, patientName: 'FROST, Malcolm (Mr)',      appointmentType: 'Diabetes review',    status: 'Completed',    chiNumber: '640283 5917', phone: '07673 234 561', notes: 'Annual diabetes review. HbA1c 71 mmol/mol — above target. Patient reluctant to add insulin. Agreed trial of SGLT2 inhibitor. Repeat bloods in three months.' },
  { id: 'dc-03', columnId: 'diabetes', type: 'appointment', startTime: '10:00', durationMins: 30, patientName: 'DUNBAR, Heather (Mrs)',    appointmentType: 'Diabetes education', status: 'In Progress',  chiNumber: '295067 8413', phone: '07495 456 782', notes: 'DESMOND structured education session for newly diagnosed type 2 diabetes. Patient diagnosed three months ago. Covering diet, exercise, medication, monitoring, and long-term complications.' },
  { id: 'dc-04', columnId: 'diabetes', type: 'appointment', startTime: '10:30', durationMins: 30, patientName: 'SEYMOUR, Robert (Mr)',     appointmentType: 'Insulin review',     status: 'Arrived',      chiNumber: '718302 6549', phone: '07817 678 903', notes: 'Insulin dose titration review. Recently commenced on basal insulin — glargine 10 units at night. Fasting glucose diary to be reviewed. Patient reporting two hypoglycaemic episodes.' },
  { id: 'dc-05', columnId: 'diabetes', type: 'appointment', startTime: '11:00', durationMins: 30, patientName: 'BARTON, Gladys (Mrs)',     appointmentType: 'Diabetes review',    status: 'Booked',       chiNumber: '463925 0781', phone: '07539 890 124', notes: 'Annual diabetes review including foot assessment, BP, weight, and HbA1c. Patient has background diabetic retinopathy — ophthalmology letter due for review.' },
  { id: 'dc-06', columnId: 'diabetes', type: 'blocked',     startTime: '11:30', durationMins: 30, blockedLabel: 'MDT discussion'          },
  { id: 'dc-07', columnId: 'diabetes', type: 'blocked',     startTime: '12:00', durationMins: 60, blockedLabel: 'Lunch'                   },
  { id: 'dc-08', columnId: 'diabetes', type: 'appointment', startTime: '13:00', durationMins: 30, patientName: 'KINGSLEY, Albert (Mr)',    appointmentType: 'New patient',        status: 'Booked',       chiNumber: '826471 0359', phone: '07361 012 345', notes: 'New patient referral from Dr Reid. Type 2 diabetes diagnosed two years ago, on metformin and sitagliptin. HbA1c persistently above 70. Full diabetes assessment to be completed.' },
  { id: 'dc-09', columnId: 'diabetes', type: 'appointment', startTime: '13:30', durationMins: 30, patientName: 'DOYLE, Mabel (Mrs)',       appointmentType: 'Follow-up',          status: 'Booked',       chiNumber: '152039 4786', phone: '07783 234 566', notes: 'Follow-up after recent emergency admission for hyperosmolar hyperglycaemic state. Now recovered. Reinforce sick-day rules, medication regime, and self-monitoring plan.' },
  { id: 'dc-10', columnId: 'diabetes', type: 'appointment', startTime: '14:00', durationMins: 45, patientName: 'FOWLER, Reginald (Mr)',    appointmentType: 'Insulin review',     status: 'Booked',       chiNumber: '704861 5293', phone: '07505 456 787', notes: 'Insulin optimisation. Patient has used mixed insulin regime for eight years. Recent Libre sensor data shows significant postprandial spikes. Consider moving to basal-bolus regime.' },
  { id: 'dc-11', columnId: 'diabetes', type: 'available',   startTime: '14:45', durationMins: 15 },
  { id: 'dc-12', columnId: 'diabetes', type: 'appointment', startTime: '15:00', durationMins: 30, patientName: 'BRADLEY, Constance (Mrs)', appointmentType: 'Specialist review',  status: 'Booked',       chiNumber: '387240 9615', phone: '07927 678 908', notes: 'Annual specialist review for type 1 diabetes on insulin pump therapy. Review pump settings and CGM data. Retinal screening result to discuss — mild maculopathy noted.' },
  { id: 'dc-13', columnId: 'diabetes', type: 'appointment', startTime: '15:30', durationMins: 30, patientName: 'MARSH, Herbert (Mr)',      appointmentType: 'Foot care',          status: 'Booked',       chiNumber: '914526 0783', phone: '07749 890 129', notes: 'Diabetic foot assessment. Patient previously treated for small foot ulcer on right sole — now healed. Annual comprehensive examination. Check peripheral neuropathy and vascular status.' },
  { id: 'dc-14', columnId: 'diabetes', type: 'appointment', startTime: '16:00', durationMins: 30, patientName: 'KEATS, Winifred (Mrs)',    appointmentType: 'Diabetes education', status: 'Booked',       chiNumber: '571348 2096', phone: '07471 012 340', notes: 'Second DAFNE education session for type 1 diabetes. Patient learning self-management of insulin doses. Review carbohydrate counting and correction dose calculations.' },
  { id: 'dc-15', columnId: 'diabetes', type: 'blocked',     startTime: '16:30', durationMins: 30, blockedLabel: 'Clinical admin'          },
];

// ─── Urgent Care ─────────────────────────────────────────────────────────────

export interface UrgentCareSlot {
  id: string;
  time: string;
  durationMins: number;
  location: string;
  clinician: string;
  clinicianRole: string;
  clinicianType: string;
  distanceMiles: number;
  isRecommended?: boolean;
  contextHint?: { text: string; variant: 'green' | 'blue' | 'pink' };
}

export interface UrgentCareLocationMeta {
  name: string;
  slotCount: number;
  availability: 'good' | 'limited' | 'scarce';
  distanceMiles: number;
}

export const URGENT_CARE_PATIENT = {
  name: 'Sarah Mitchell',
  chiNumber: '485777 3456',
  dob: '15/03/1978',
  age: 46,
  postcode: 'M1 4BT',
  phone: '07700 900123',
};

export const URGENT_CARE_LOCATION_META: UrgentCareLocationMeta[] = [
  { name: 'Central Medical Clinic',  slotCount: 17, availability: 'good',   distanceMiles: 0.8 },
  { name: 'Riverside Health Centre', slotCount: 11, availability: 'good',   distanceMiles: 1.2 },
  { name: 'Oakwood Surgery',         slotCount: 5,  availability: 'scarce', distanceMiles: 1.9 },
  { name: 'Park View Medical',       slotCount: 3,  availability: 'scarce', distanceMiles: 2.3 },
];

export const URGENT_CARE_CLINICIAN_TYPES = [
  { id: 'gp',     label: 'General Practitioner', count: 28 },
  { id: 'nurse',  label: 'Practice Nurse',        count: 6  },
  { id: 'physio', label: 'Physiotherapist',       count: 1  },
  { id: 'mh',     label: 'Mental Health',         count: 1  },
];

export const URGENT_CARE_SLOTS: UrgentCareSlot[] = [
  // ─── Recommended ─────────────────────────────────────────────────────────
  { id: 'uc-r1', time: '09:00', durationMins: 15, location: 'Central Medical Clinic',  clinician: 'Dr. Sarah Chen',    clinicianRole: 'GP',    clinicianType: 'General Practitioner', distanceMiles: 0.8, isRecommended: true, contextHint: { text: 'Earliest available at nearest location', variant: 'green' } },
  { id: 'uc-r2', time: '09:00', durationMins: 20, location: 'Riverside Health Centre', clinician: 'Nurse Maria Garcia', clinicianRole: 'Nurse', clinicianType: 'Practice Nurse',        distanceMiles: 1.2, isRecommended: true, contextHint: { text: 'Same time, alternative location',       variant: 'blue'  } },
  { id: 'uc-r3', time: '09:15', durationMins: 15, location: 'Central Medical Clinic',  clinician: 'Dr. Sarah Chen',    clinicianRole: 'GP',    clinicianType: 'General Practitioner', distanceMiles: 0.8, isRecommended: true, contextHint: { text: 'Next available at nearest location',    variant: 'pink'  } },
  // ─── All slots ────────────────────────────────────────────────────────────
  { id: 'uc-a1',  time: '09:00', durationMins: 15, location: 'Central Medical Clinic',  clinician: 'Dr. Sarah Chen',    clinicianRole: 'GP',    clinicianType: 'General Practitioner', distanceMiles: 0.8 },
  { id: 'uc-a2',  time: '09:00', durationMins: 20, location: 'Riverside Health Centre', clinician: 'Nurse Maria Garcia', clinicianRole: 'Nurse', clinicianType: 'Practice Nurse',        distanceMiles: 1.2 },
  { id: 'uc-a3',  time: '09:15', durationMins: 15, location: 'Central Medical Clinic',  clinician: 'Dr. Sarah Chen',    clinicianRole: 'GP',    clinicianType: 'General Practitioner', distanceMiles: 0.8 },
  { id: 'uc-a4',  time: '09:30', durationMins: 15, location: 'Central Medical Clinic',  clinician: 'Dr. James Wilson',  clinicianRole: 'GP',    clinicianType: 'General Practitioner', distanceMiles: 0.8 },
  { id: 'uc-a5',  time: '09:45', durationMins: 20, location: 'Riverside Health Centre', clinician: 'Nurse Maria Garcia', clinicianRole: 'Nurse', clinicianType: 'Practice Nurse',        distanceMiles: 1.2 },
  { id: 'uc-a6',  time: '10:00', durationMins: 15, location: 'Central Medical Clinic',  clinician: 'Dr. Sarah Chen',    clinicianRole: 'GP',    clinicianType: 'General Practitioner', distanceMiles: 0.8 },
  { id: 'uc-a7',  time: '10:00', durationMins: 20, location: 'Oakwood Surgery',         clinician: 'Dr. Priya Sharma',  clinicianRole: 'GP',    clinicianType: 'General Practitioner', distanceMiles: 1.9 },
  { id: 'uc-a8',  time: '10:15', durationMins: 20, location: 'Central Medical Clinic',  clinician: 'Dr. James Wilson',  clinicianRole: 'GP',    clinicianType: 'General Practitioner', distanceMiles: 0.8 },
  { id: 'uc-a9',  time: '10:30', durationMins: 15, location: 'Riverside Health Centre', clinician: 'Nurse Maria Garcia', clinicianRole: 'Nurse', clinicianType: 'Practice Nurse',        distanceMiles: 1.2 },
  { id: 'uc-a10', time: '10:45', durationMins: 15, location: 'Central Medical Clinic',  clinician: 'Dr. Sarah Chen',    clinicianRole: 'GP',    clinicianType: 'General Practitioner', distanceMiles: 0.8 },
  { id: 'uc-a11', time: '11:00', durationMins: 15, location: 'Oakwood Surgery',         clinician: 'Dr. Priya Sharma',  clinicianRole: 'GP',    clinicianType: 'General Practitioner', distanceMiles: 1.9 },
  { id: 'uc-a12', time: '11:30', durationMins: 20, location: 'Central Medical Clinic',  clinician: 'Dr. James Wilson',  clinicianRole: 'GP',    clinicianType: 'General Practitioner', distanceMiles: 0.8 },
  { id: 'uc-a13', time: '14:00', durationMins: 15, location: 'Central Medical Clinic',  clinician: 'Dr. Sarah Chen',    clinicianRole: 'GP',    clinicianType: 'General Practitioner', distanceMiles: 0.8 },
  { id: 'uc-a14', time: '14:30', durationMins: 10, location: 'Park View Medical',       clinician: 'Dr. Thomas Burke',  clinicianRole: 'GP',    clinicianType: 'General Practitioner', distanceMiles: 2.3 },
  { id: 'uc-a15', time: '15:00', durationMins: 15, location: 'Riverside Health Centre', clinician: 'Nurse Maria Garcia', clinicianRole: 'Nurse', clinicianType: 'Practice Nurse',        distanceMiles: 1.2 },
  { id: 'uc-a16', time: '15:30', durationMins: 20, location: 'Central Medical Clinic',  clinician: 'Dr. Sarah Chen',    clinicianRole: 'GP',    clinicianType: 'General Practitioner', distanceMiles: 0.8 },
];
